title: Vincent Mutua # your name (or website title) here
logo: "/images/Vincent_profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  CONFIDENT, ABSTRACT, ASSERTIVE, OPEN TO CHANGE, ENTHUSIASTIC, HIGH-ENERGY
  <br><br>
  Logic, patience, communication, and attention to detail are my underlying strengths. I have a knack for not panicking in the face of complexity. I break things down into manageable chunks, and tackle them with the tools at my disposal.Things I'm into: planning, building structures, thinking in systems, puzzles, adapting to change and learning new technologies.
  <br><br>
  <a href="https://www.linkedin.com/in/vincent-mutua-b4b87724/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-cayman
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
